SET TERM ^;
CREATE TRIGGER DRUG_NOMENCLATURE_VAR_BIU FOR DRUG_NOMENCLATURE_VAR
ACTIVE BEFORE INSERT OR UPDATE
POSITION 0
AS
DECLARE COUNT_EXISTENT INTEGER;
BEGIN
  /* set id if null */
  IF(NEW.DNV_ID IS NULL) THEN
    NEW.DNV_ID = NEXT VALUE FOR NOMENCLATURES_VAR_SEQ;
  /* check existent */
  SELECT COUNT(*)
  FROM
    DRUG_NOMENCLATURE_VAR A
  WHERE
    A.DNV_DRUG = NEW.DNV_DRUG
    AND
    A.DNV_NOMENCLATURE = NEW.DNV_NOMENCLATURE
    AND
    A.DNV_ID <> NEW.DNV_ID
    INTO
    :COUNT_EXISTENT;
    
    /* if count_existent > 0 then exception */
    IF(COUNT_EXISTENT > 0) THEN
      EXCEPTION EXISTENT_VAR_E;
END ^
SET TERM ;^