SET TERM ^;
CREATE TRIGGER DRUG_GROUPS_BIU FOR DRUG_GROUPS
ACTIVE BEFORE INSERT OR UPDATE
POSITION 0
AS
BEGIN
  /* set id if null */
  IF(NEW.DG_ID IS NULL) THEN
    NEW.DG_ID = NEXT VALUE FOR GROUPS_SEQ;
    
  /* set code */
  IF((NEW.DG_CODE IS NULL) OR (CHAR_LENGTH(NEW.DG_CODE) < 1)) THEN
    NEW.DG_CODE = 'DG-' || CAST(NEW.DG_ID AS VARCHAR(15));
END^
SET TERM ;^