SELECT WAREHOUSE_ID, WAREHOUSE_CODE, WAREHOUSE_NAME FROM
(SELECT
  A.DW_ID AS WAREHOUSE_ID,
  A.DW_CODE AS WAREHOUSE_CODE,
  A.DW_NAME AS WAREHOUSE_NAME
FROM
  DRUG_WAREHOUSE A
  
UNION
SELECT
  B.AW_ID AS WAREHOUSE_ID,
  B.AW_CODE AS WAREHOUSE_CODE,
  B.AW_NAME AS WAREHOUSE_NAME
FROM
  APPLIANCES_WAREHOUSE B
  
UNION
SELECT
  C.HEW_ID AS WAREHOUSE_ID,
  C.HEW_CODE AS WAREHOUSE_CODE,
  C.HEW_NAME AS WAREHOUSE_NAME
FROM
  HEQUIPMENT_WAREHOUSE C
)
ORDER BY
  WAREHOUSE_NAME
