CREATE VIEW PRODUCTS_ALL_V
AS

SELECT 
  PRODUCT_ID,
  PRODUCT_CODE,
  PRODUCT_NAME,
  PRODUCT_BARCODE,
  PRODUCT_GROUP,
  PRODUCT_MEASURE_CODE,
  PRODUCT_MEASURE,
  PRODUCT_TAX,
  PRODUCT_TAX_VALUE,
  PRODUCT_PIECES
FROM
  (
    SELECT
      A.D_ID AS PRODUCT_ID,
      A.D_CODE AS PRODUCT_CODE,
      A.D_NAME AS PRODUCT_NAME,
      A.D_BARCODE AS PRODUCT_BARCODE,
      A.DRUG_GROUP_NAME AS PRODUCT_GROUP,
      A.MEASURE_CODE AS PRODUCT_MEASURE_CODE,
      A.MEASURE_NAME AS PRODUCT_MEASURE,
      A.TAX_CODE AS PRODUCT_TAX,
      A.TAX_VALUE AS PRODUCT_TAX_VALUE,
      A.D_PIECES AS PRODUCT_PIECES
    FROM
      DRUGS_V A
      
    UNION
    
    SELECT
      B.F_ID AS PRODUCT_ID,
      B.F_CODE AS PRODUCT_CODE,
      B.F_NAME AS PRODUCT_NAME,
      B.F_BARCODE AS PRODUCT_BARCODE,
      B.GROUP_NAME AS PRODUCT_GROUP,
      B.MEASURE_CODE AS PRODUCT_MEASURE_CODE,
      B.MEASURE_NAME AS PRODUCT_MEASURE,
      B.TAX_CODE AS PRODUCT_TAX,
      B.TAX_VALUE AS PRODUCT_TAX_VALUE,
      B.F_PIECES AS PRODUCT_PIECES
    FROM
      FOOD_V B
      
    UNION
    
    SELECT
      C.HE_ID AS PRODUCT_ID,
      C.HE_CODE AS PRODUCT_CODE,
      C.HE_NAME AS PRODUCT_NAME,
      C.HE_BARCODE AS PRODUCT_BARCODE,
      C.GROUP_NAME AS PRODUCT_GROUP,
      C.MEASURE_CODE AS PRODUCT_MEASURE_CODE,
      C.MEASURE_NAME AS PRODUCT_MEASURE,
      C.TAX_CODE AS PRODUCT_CODE,
      C.TAX_VALUE AS PRODUCT_TAX_VALUE,
      C.HE_PIECES AS PRODUCT_PIECES
    FROM
      HOSPITAL_EQUIPMENT_V C
      
    UNION
    
    SELECT
      D.HM_ID AS PRODUCT_ID,
      D.HM_CODE AS PRODUCT_CODE,
      D.HM_NAME AS PRODUCT_NAME,
      D.HM_BARCODE AS PRODUCT_BARCODE,
      D.GROUP_NAME AS PRODUCT_GROUP,
      D.MEASURE_CODE AS PRODUCT_MEASURE_CODE,
      D.MEASURE_NAME AS PRODUCT_MEASURE,
      D.TAX_CODE AS PRODUCT_TAX,
      D.TAX_VALUE AS PRODUCT_TAX_VALUE,
      D.HM_PIECES AS PRODUCT_PIECES
    FROM
      HYGIENE_MATERIAL_V D
      
    UNION
    
    SELECT
      E.MA_ID AS PRODUCT_ID,
      E.MA_CODE AS PRODUCT_CODE,
      E.MA_NAME AS PRODUCT_NAME,
      E.MA_BARCODE AS PRODUCT_BARCODE,
      E.GROUP_NAME AS PRODUCT_GROUP,
      E.MEASURE_CODE AS PRODUCT_MEASURE_CODE,
      E.MEASURE_NAME AS PRODUCT_MEASURE,
      E.TAX_CODE AS PRODUCT_TAX,
      E.TAX_VALUE AS PRODUCT_TAX_VALUE,
      E.MA_PIECES AS PRODUCT_PIECES
    FROM
      MATERIALS_ACCESSORIES_V E
      
    UNION
    
    SELECT
      F.MA_ID AS PRODUCT_ID,
      F.MA_CODE AS PRODUCT_CODE,
      F.MA_NAME AS PRODUCT_NAME,
      F.MA_BARCODE AS PRODUCT_BARCODE,
      F.GROUP_NAME AS PRODUCT_GROUP,
      F.MEASURE_CODE AS PRODUCT_MEASURE_CODE,
      F.MEASURE_NAME AS PRODUCT_MEASURE,
      F.TAX_CODE AS PRODUCT_TAX,
      F.TAX_VALUE AS PRODUCT_TAX_VALUE,
      F.MA_PIECES AS PRODUCT_PIECES  
    FROM
      MEDICINE_APPLIANCES_V F
      
    UNION
    
    SELECT
      G.OM_ID AS PRODUCT_ID,
      G.OM_CODE AS PRODUCT_CODE,
      G.OM_NAME AS PRODUCT_NAME,
      G.OM_BARCODE AS PRODUCT_BARCODE,
      G.GROUP_NAME AS PRODUCT_GROUP,
      G.MEASURE_CODE AS PRODUCT_MEASURE_CODE,
      G.MEASURE_NAME AS PRODUCT_MEASURE,
      G.TAX_CODE AS PRODUCT_TAX,
      G.TAX_VALUE AS PRODUCT_TAX_VALUE,
      G.OM_PIECES AS PRODUCT_PIECES
    FROM
      OFFICE_MATERIAL_V G
      
    UNION
    
    SELECT
      H.PM_ID AS PRODUCT_ID,
      H.PM_CODE AS PRODUCT_CODE,
      H.PM_NAME AS PRODUCT_NAME,
      H.PM_BARCODE AS PRODUCT_BARCODE,
      H.PM_GROUP_NAME AS PRODUCT_GROUP,
      H.MEASURE_CODE AS PRODUCT_MEASURE_CODE,
      H.MEASURE_NAME AS PRODUCT_MEASURE,
      H.TAX_CODE AS PRODUCT_TAX,
      H.TAX_VALUE AS PRODUCT_TAX_VALUE,
      H.PM_PIECES AS PRODUCT_PIECES
    FROM
      PHARMACY_MATERIAL_V H
  )
ORDER BY
  PRODUCT_NAME
  
  
  
  
  
  
  
  
  