CREATE VIEW DRUG_STRONG_V
AS
SELECT
  A.DS_ID,
  A.DS_DRUG,
  A.DS_MEASURE,
  A.DS_VALUE,
  B.D_CODE AS DRUG_CODE,
  B.D_NAME AS DRUG_NAME,
  C.M_CODE AS MEASURE_CODE,
  C.M_NAME AS MEASURE_NAME
FROM
  DRUG_STRONG A,
  DRUGS B,
  MEASURE C
WHERE
  B.D_ID = A.DS_DRUG
  AND
  C.M_ID = A.DS_MEASURE
ORDER BY
  A.DS_ID