SET TERM ^ ;
CREATE TRIGGER APPLIANCES_HPWAREHOUSE_BIU FOR APPLIANCES_HPWAREHOUSE ACTIVE
BEFORE INSERT OR UPDATE POSITION 0
AS
BEGIN
  /* set ID if null */
  IF(NEW.AHPW_ID IS NULL) THEN  
    NEW.AHPW_ID = NEXT VALUE FOR WAREHOUSE_SEQ;
  
  /* set code if null or empty_string */
  IF((NEW.AHPW_CODE IS NULL) OR (CHAR_LENGTH(NEW.AHPW_CODE) < 1)) THEN
    NEW.AHPW_CODE = 'AHPW-' || CAST(NEW.AHPW_ID AS VARCHAR(15));
    
  /* set address if null or wmpty string */
  IF((NEW.AHPW_ADDRESS IS NULL) OR (CHAR_LENGTH(NEW.AHPW_ADDRESS) < 1)) THEN
    NEW.AHPW_ADDRESS = 'Nepoznata';
END^
SET TERM ; ^
