CREATE TABLE APPLIANCES_HPWAREHOUSE (
  AHPW_ID INTEGER NOT NULL PRIMARY KEY,
  AHPW_CODE VARCHAR(30) NOT NULL UNIQUE,
  AHPW_NAME VARCHAR(70) NOT NULL UNIQUE,
  AHPW_LOCATION INTEGER NOT NULL,
  AHPW_ADDRESS VARCHAR(70) NOT NULL,
  AHPW_PHONE VARCHAR(25),
  AHPW_FAX VARCHAR(25),
  AHPW_MAIL VARCHAR(25),
  AHPW_DEPARTMENT INTEGER NOT NULL,
  CONSTRAINT APPLIANCESHPW_FK_LOCATION FOREIGN KEY(AHPW_LOCATION) REFERENCES LOCATION(L_ID),
  CONSTRAINT APPLIANCESHPW_FK_DEPARTMENT FOREIGN KEY(AHPW_DEPARTMENT) REFERENCES DEPARTMENT(D_ID)
  )